# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_test_linbtn.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from QSwitchControl import SwitchControl

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(475, 0))
        self.menu.setStyleSheet("#menu{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.5, x3:0, y3:1 stop:0 #AABCDB , stop:1 #9CC4B2, stop:2 #9CC4B2);\n"
" border-radius: 10px;\n"
" border: none;\n"
"}\n"
"")
        self.menu.setObjectName("menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 45))
        self.widget_7.setObjectName("widget_7")
        # self.checkBox = QtWidgets.QCheckBox(self.widget_7)
        # self.checkBox.setGeometry(QtCore.QRect(81, 15, 82, 19))
        # self.checkBox.setObjectName("checkBox")
        self.checkBox = SwitchControl(self.widget_7, bg_color="#89D2DC", circle_color="#393D3F", active_color="#9CC4B2")
        self.checkBox.setGeometry(QtCore.QRect(85, 10, 30, 20))
        self.checkBox.setObjectName("checkBox")
        self.closeButton = QtWidgets.QPushButton(self.widget_7)
        self.closeButton.setGeometry(QtCore.QRect(11, 11, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.closeButton.setStyleSheet("background-color:transparent")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setIconSize(QtCore.QSize(15, 15))
        self.closeButton.setObjectName("closeButton")
        self.miniButton = QtWidgets.QPushButton(self.widget_7)
        self.miniButton.setGeometry(QtCore.QRect(46, 11, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.miniButton.sizePolicy().hasHeightForWidth())
        self.miniButton.setSizePolicy(sizePolicy)
        self.miniButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.miniButton.setStyleSheet("background-color:transparent")
        self.miniButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icon/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.miniButton.setIcon(icon1)
        self.miniButton.setIconSize(QtCore.QSize(15, 15))
        self.miniButton.setObjectName("miniButton")
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.widget_8)
        self.stackedWidget_main.setGeometry(QtCore.QRect(0, 0, 458, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_main.sizePolicy().hasHeightForWidth())
        self.stackedWidget_main.setSizePolicy(sizePolicy)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.Description = QtWidgets.QLabel(self.page_5)
        self.Description.setGeometry(QtCore.QRect(30, 220, 375, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Description.setFont(font)
        self.Description.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Description.setTextFormat(QtCore.Qt.MarkdownText)
        self.Description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Description.setObjectName("Description")
        self.Title = QtWidgets.QLabel(self.page_5)
        self.Title.setGeometry(QtCore.QRect(30, 41, 400, 80))
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.SecondTitle = QtWidgets.QLabel(self.page_5)
        self.SecondTitle.setGeometry(QtCore.QRect(30, 140, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SecondTitle.setFont(font)
        self.SecondTitle.setTextFormat(QtCore.Qt.RichText)
        self.SecondTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.SecondTitle.setObjectName("SecondTitle")
        self.Warning = QtWidgets.QLabel(self.page_5)
        self.Warning.setGeometry(QtCore.QRect(60, 350, 350, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Warning.setFont(font)
        self.Warning.setTextFormat(QtCore.Qt.MarkdownText)
        self.Warning.setScaledContents(False)
        self.Warning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Warning.setWordWrap(True)
        self.Warning.setObjectName("Warning")
        self.stackedWidget_main.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.Warning_2 = QtWidgets.QLabel(self.page_6)
        self.Warning_2.setGeometry(QtCore.QRect(60, 350, 350, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Warning_2.setFont(font)
        self.Warning_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.Warning_2.setScaledContents(False)
        self.Warning_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Warning_2.setWordWrap(True)
        self.Warning_2.setObjectName("Warning_2")
        self.SecondTitle_2 = QtWidgets.QLabel(self.page_6)
        self.SecondTitle_2.setGeometry(QtCore.QRect(30, 140, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SecondTitle_2.setFont(font)
        self.SecondTitle_2.setTextFormat(QtCore.Qt.RichText)
        self.SecondTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.SecondTitle_2.setObjectName("SecondTitle_2")
        self.Description_2 = QtWidgets.QLabel(self.page_6)
        self.Description_2.setGeometry(QtCore.QRect(30, 220, 375, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Description_2.setFont(font)
        self.Description_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Description_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.Description_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Description_2.setObjectName("Description_2")
        self.Title_2 = QtWidgets.QLabel(self.page_6)
        self.Title_2.setGeometry(QtCore.QRect(30, 41, 400, 80))
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Title_2.setFont(font)
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setObjectName("Title_2")
        self.stackedWidget_main.addWidget(self.page_6)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.horizontalLayout.addWidget(self.menu)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setMaximumSize(QtCore.QSize(16777215, 500))
        self.input.setStyleSheet("#input{\n"
" background-color: #393D3F;\n"
" border-top-right-radius: 10px;\n"
" border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"")
        self.input.setObjectName("input")
        self.stackedWidget_input = QtWidgets.QStackedWidget(self.input)
        self.stackedWidget_input.setGeometry(QtCore.QRect(0, 0, 425, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_input.sizePolicy().hasHeightForWidth())
        self.stackedWidget_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stackedWidget_input.setFont(font)
        self.stackedWidget_input.setStyleSheet("")
        self.stackedWidget_input.setObjectName("stackedWidget_input")
        self.page_7 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.page_7.setFont(font)
        self.page_7.setStyleSheet("QLabel {\n"
" color: #fff;\n"
"}\n"
"\n"
"#bu_input_path,\n"
"#bu_wb_path,\n"
"#bu_output_path {\n"
" color: #000;\n"
" background-color: #9CC4B2;\n"
" border-radius: 10px;\n"
" border: 2px solid #9CC4B2;\n"
"}\n"
"\n"
"#bu_input, #bu_output, #bu_wb {\n"
" color: #000;\n"
" background-color: #9CC4B2;\n"
" border-radius: 10px;\n"
" border: 2px solid #9CC4B2;\n"
"}\n"
"\n"
"#bu_input_button,\n"
"#bu_wb_button,\n"
"#bu_output_button {\n"
" color: #000;\n"
" background-color: #9CC4B2;\n"
" border-radius: 10px;\n"
" border: 4px solid #9CC4B2;\n"
"}\n"
"\n"
"#bu_ti_col,\n"
"#bu_ab_col,\n"
"#bu_label_col {\n"
" background-color: #393D3F;\n"
" border: none;\n"
" border-bottom: 2px solid #9CC4B2;\n"
" color: #B2B2B2;\n"
" padding-bottom: 3px;\n"
"}\n"
"")
        self.page_7.setObjectName("page_7")
        self.ab_col = QtWidgets.QLabel(self.page_7)
        self.ab_col.setGeometry(QtCore.QRect(50, 320, 100, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ab_col.setFont(font)
        self.ab_col.setObjectName("ab_col")
        self.label_7 = QtWidgets.QLabel(self.page_7)
        self.label_7.setGeometry(QtCore.QRect(50, 180, 115, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.bu_exeButton = QtWidgets.QPushButton(self.page_7)
        self.bu_exeButton.setGeometry(QtCore.QRect(175, 417, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_exeButton.sizePolicy().hasHeightForWidth())
        self.bu_exeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bu_exeButton.setFont(font)
        self.bu_exeButton.setStyleSheet("QPushButton#bu_exeButton {\n"
" color: #fff;\n"
" background-color: #393D3F;\n"
" border-radius: 14px;\n"
" border: 2px solid #9CC4B2;\n"
"}\n"
"\n"
"QPushButton#bu_exeButton:hover, press {\n"
" color: #393D3F;\n"
" background-color: #9CC4B2;\n"
" border-radius: 14px;\n"
" border: 2px solid #9CC4B2;\n"
"}")
        self.bu_exeButton.setFlat(False)
        self.bu_exeButton.setObjectName("bu_exeButton")
        self.label_6 = QtWidgets.QLabel(self.page_7)
        self.label_6.setGeometry(QtCore.QRect(50, 140, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.page_7)
        self.label_5.setGeometry(QtCore.QRect(50, 100, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.page_7)
        self.label_8.setGeometry(QtCore.QRect(50, 280, 100, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.page_7)
        self.label_10.setGeometry(QtCore.QRect(50, 360, 100, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.bu_label_col = QtWidgets.QLineEdit(self.page_7)
        self.bu_label_col.setGeometry(QtCore.QRect(155, 357, 230, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_label_col.sizePolicy().hasHeightForWidth())
        self.bu_label_col.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bu_label_col.setFont(font)
        self.bu_label_col.setObjectName("bu_label_col")
        self.bu_ti_col = QtWidgets.QLineEdit(self.page_7)
        self.bu_ti_col.setGeometry(QtCore.QRect(155, 277, 230, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_ti_col.sizePolicy().hasHeightForWidth())
        self.bu_ti_col.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bu_ti_col.setFont(font)
        self.bu_ti_col.setStyleSheet("")
        self.bu_ti_col.setObjectName("bu_ti_col")
        self.bu_ab_col = QtWidgets.QLineEdit(self.page_7)
        self.bu_ab_col.setGeometry(QtCore.QRect(155, 317, 230, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_ab_col.sizePolicy().hasHeightForWidth())
        self.bu_ab_col.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bu_ab_col.setFont(font)
        self.bu_ab_col.setObjectName("bu_ab_col")
        self.bu_input = QtWidgets.QWidget(self.page_7)
        self.bu_input.setGeometry(QtCore.QRect(155, 97, 230, 25))
        self.bu_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bu_input.setStyleSheet("#widget {\n"
" color: #000;\n"
" background-color: #9CC4B2;\n"
" border-radius: 10px;\n"
" border: 2px solid #9CC4B2;\n"
"}")
        self.bu_input.setObjectName("bu_input")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bu_input)
        self.horizontalLayout_2.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bu_input_path = QtWidgets.QLineEdit(self.bu_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_input_path.sizePolicy().hasHeightForWidth())
        self.bu_input_path.setSizePolicy(sizePolicy)
        self.bu_input_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.bu_input_path.setFont(font)
        self.bu_input_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bu_input_path.setObjectName("bu_input_path")
        self.horizontalLayout_2.addWidget(self.bu_input_path)
        self.bu_input_button = QtWidgets.QPushButton(self.bu_input)
        self.bu_input_button.setStyleSheet("")
        self.bu_input_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icon/search_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bu_input_button.setIcon(icon2)
        self.bu_input_button.setAutoRepeat(False)
        self.bu_input_button.setObjectName("bu_input_button")
        self.horizontalLayout_2.addWidget(self.bu_input_button)
        self.label = QtWidgets.QLabel(self.page_7)
        self.label.setGeometry(QtCore.QRect(40, 47, 50, 40))
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bu_wb = QtWidgets.QWidget(self.page_7)
        self.bu_wb.setGeometry(QtCore.QRect(155, 137, 230, 25))
        self.bu_wb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bu_wb.setStyleSheet("#widget {\n"
" color: #000;\n"
" background-color: #9CC4B2;\n"
" border-radius: 10px;\n"
" border: 2px solid #9CC4B2;\n"
"}")
        self.bu_wb.setObjectName("bu_wb")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bu_wb)
        self.horizontalLayout_3.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bu_wb_path = QtWidgets.QLineEdit(self.bu_wb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_wb_path.sizePolicy().hasHeightForWidth())
        self.bu_wb_path.setSizePolicy(sizePolicy)
        self.bu_wb_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.bu_wb_path.setFont(font)
        self.bu_wb_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bu_wb_path.setObjectName("bu_wb_path")
        self.horizontalLayout_3.addWidget(self.bu_wb_path)
        self.bu_wb_button = QtWidgets.QPushButton(self.bu_wb)
        self.bu_wb_button.setStyleSheet("")
        self.bu_wb_button.setText("")
        self.bu_wb_button.setIcon(icon2)
        self.bu_wb_button.setAutoRepeat(False)
        self.bu_wb_button.setObjectName("bu_wb_button")
        self.horizontalLayout_3.addWidget(self.bu_wb_button)
        self.bu_output = QtWidgets.QWidget(self.page_7)
        self.bu_output.setGeometry(QtCore.QRect(155, 177, 230, 25))
        self.bu_output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bu_output.setStyleSheet("#bu_output {\n"
" color: #000;\n"
" background-color: #9CC4B2;\n"
" border-radius: 10px;\n"
" border: 2px solid #9CC4B2;\n"
"}")
        self.bu_output.setObjectName("bu_output")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bu_output)
        self.horizontalLayout_4.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bu_output_path = QtWidgets.QLineEdit(self.bu_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu_output_path.sizePolicy().hasHeightForWidth())
        self.bu_output_path.setSizePolicy(sizePolicy)
        self.bu_output_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.bu_output_path.setFont(font)
        self.bu_output_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bu_output_path.setObjectName("bu_output_path")
        self.horizontalLayout_4.addWidget(self.bu_output_path)
        self.bu_output_button = QtWidgets.QPushButton(self.bu_output)
        self.bu_output_button.setStyleSheet("")
        self.bu_output_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/icon/search_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bu_output_button.setIcon(icon3)
        self.bu_output_button.setAutoRepeat(False)
        self.bu_output_button.setObjectName("bu_output_button")
        self.horizontalLayout_4.addWidget(self.bu_output_button)
        self.label_2 = QtWidgets.QLabel(self.page_7)
        self.label_2.setGeometry(QtCore.QRect(40, 227, 150, 40))
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget_input.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setStyleSheet("QLabel {\n"
" color: #fff;\n"
"}\n"
"\n"
"#pre_input_path,\n"
"#pre_wb_path,\n"
"#pre_model_path,\n"
"#pre_output_path {\n"
" color: #000;\n"
" background-color: #89D2DC;\n"
" border-radius: 10px;\n"
" border: 2px solid #89D2DC;\n"
"}\n"
"\n"
"#pre_input,\n"
"#pre_output,\n"
"#pre_wb,\n"
"#pre_model {\n"
" color: #000;\n"
" background-color: #89D2DC;\n"
" border-radius: 10px;\n"
" border: 2px solid #89D2DC;\n"
"}\n"
"\n"
"#pre_input_button,\n"
"#pre_wb_button,\n"
"#pre_output_button,\n"
"#pre_model_button {\n"
" color: #000;\n"
" background-color: #89D2DC;\n"
" border-radius: 10px;\n"
" border: 4px solid #89D2DC;\n"
"}\n"
"\n"
"#pre_ti_col,\n"
"#pre_ab_col {\n"
" background-color: #393D3F;\n"
" border: none;\n"
" border-bottom: 2px solid #89D2DC;\n"
" color: #B2B2B2;\n"
" padding-bottom: 3px;\n"
"}\n"
"")
        self.page_8.setObjectName("page_8")
        self.label_9 = QtWidgets.QLabel(self.page_8)
        self.label_9.setGeometry(QtCore.QRect(50, 100, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pre_exeButton = QtWidgets.QPushButton(self.page_8)
        self.pre_exeButton.setGeometry(QtCore.QRect(175, 417, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_exeButton.sizePolicy().hasHeightForWidth())
        self.pre_exeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pre_exeButton.setFont(font)
        self.pre_exeButton.setStyleSheet("QPushButton#pre_exeButton {\n"
" color: #fff;\n"
" background-color: #393D3F;\n"
" border-radius: 14px;\n"
" border: 2px solid #89D2DC;\n"
"}\n"
"\n"
"QPushButton#pre_exeButton:hover, press {\n"
" color: #393D3F;\n"
" background-color: #89D2DC;\n"
" border-radius: 14px;\n"
" border: 2px solid #89D2DC;\n"
"}")
        self.pre_exeButton.setFlat(False)
        self.pre_exeButton.setObjectName("pre_exeButton")
        self.pre_wb = QtWidgets.QWidget(self.page_8)
        self.pre_wb.setGeometry(QtCore.QRect(155, 137, 230, 25))
        self.pre_wb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_wb.setStyleSheet("")
        self.pre_wb.setObjectName("pre_wb")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.pre_wb)
        self.horizontalLayout_8.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pre_wb_path = QtWidgets.QLineEdit(self.pre_wb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_wb_path.sizePolicy().hasHeightForWidth())
        self.pre_wb_path.setSizePolicy(sizePolicy)
        self.pre_wb_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pre_wb_path.setFont(font)
        self.pre_wb_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_wb_path.setObjectName("pre_wb_path")
        self.horizontalLayout_8.addWidget(self.pre_wb_path)
        self.pre_wb_button = QtWidgets.QPushButton(self.pre_wb)
        self.pre_wb_button.setStyleSheet("")
        self.pre_wb_button.setText("")
        self.pre_wb_button.setIcon(icon2)
        self.pre_wb_button.setAutoRepeat(False)
        self.pre_wb_button.setObjectName("pre_wb_button")
        self.horizontalLayout_8.addWidget(self.pre_wb_button)
        self.pre_output = QtWidgets.QWidget(self.page_8)
        self.pre_output.setGeometry(QtCore.QRect(155, 217, 230, 25))
        self.pre_output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_output.setStyleSheet("")
        self.pre_output.setObjectName("pre_output")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.pre_output)
        self.horizontalLayout_9.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pre_output_path = QtWidgets.QLineEdit(self.pre_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_output_path.sizePolicy().hasHeightForWidth())
        self.pre_output_path.setSizePolicy(sizePolicy)
        self.pre_output_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pre_output_path.setFont(font)
        self.pre_output_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_output_path.setObjectName("pre_output_path")
        self.horizontalLayout_9.addWidget(self.pre_output_path)
        self.pre_output_button = QtWidgets.QPushButton(self.pre_output)
        self.pre_output_button.setStyleSheet("")
        self.pre_output_button.setText("")
        self.pre_output_button.setIcon(icon3)
        self.pre_output_button.setAutoRepeat(False)
        self.pre_output_button.setObjectName("pre_output_button")
        self.horizontalLayout_9.addWidget(self.pre_output_button)
        self.pre_ti_col = QtWidgets.QLineEdit(self.page_8)
        self.pre_ti_col.setGeometry(QtCore.QRect(155, 317, 230, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_ti_col.sizePolicy().hasHeightForWidth())
        self.pre_ti_col.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pre_ti_col.setFont(font)
        self.pre_ti_col.setObjectName("pre_ti_col")
        self.pre_ab_col = QtWidgets.QLineEdit(self.page_8)
        self.pre_ab_col.setGeometry(QtCore.QRect(155, 357, 230, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_ab_col.sizePolicy().hasHeightForWidth())
        self.pre_ab_col.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pre_ab_col.setFont(font)
        self.pre_ab_col.setObjectName("pre_ab_col")
        self.label_3 = QtWidgets.QLabel(self.page_8)
        self.label_3.setGeometry(QtCore.QRect(40, 47, 50, 40))
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ab_col_2 = QtWidgets.QLabel(self.page_8)
        self.ab_col_2.setGeometry(QtCore.QRect(50, 360, 100, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ab_col_2.setFont(font)
        self.ab_col_2.setObjectName("ab_col_2")
        self.label_4 = QtWidgets.QLabel(self.page_8)
        self.label_4.setGeometry(QtCore.QRect(40, 267, 150, 40))
        font = QtGui.QFont()
        font.setFamily("SemplicitaPro")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.page_8)
        self.label_11.setGeometry(QtCore.QRect(50, 220, 115, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_8)
        self.label_12.setGeometry(QtCore.QRect(50, 320, 100, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pre_input = QtWidgets.QWidget(self.page_8)
        self.pre_input.setGeometry(QtCore.QRect(155, 97, 230, 25))
        self.pre_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_input.setStyleSheet("")
        self.pre_input.setObjectName("pre_input")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.pre_input)
        self.horizontalLayout_10.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pre_input_path = QtWidgets.QLineEdit(self.pre_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_input_path.sizePolicy().hasHeightForWidth())
        self.pre_input_path.setSizePolicy(sizePolicy)
        self.pre_input_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pre_input_path.setFont(font)
        self.pre_input_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_input_path.setObjectName("pre_input_path")
        self.horizontalLayout_10.addWidget(self.pre_input_path)
        self.pre_input_button = QtWidgets.QPushButton(self.pre_input)
        self.pre_input_button.setStyleSheet("")
        self.pre_input_button.setText("")
        self.pre_input_button.setIcon(icon2)
        self.pre_input_button.setAutoRepeat(False)
        self.pre_input_button.setObjectName("pre_input_button")
        self.horizontalLayout_10.addWidget(self.pre_input_button)
        self.label_14 = QtWidgets.QLabel(self.page_8)
        self.label_14.setGeometry(QtCore.QRect(50, 140, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pre_model = QtWidgets.QWidget(self.page_8)
        self.pre_model.setGeometry(QtCore.QRect(155, 177, 230, 25))
        self.pre_model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_model.setStyleSheet("")
        self.pre_model.setObjectName("pre_model")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.pre_model)
        self.horizontalLayout_11.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pre_model_path = QtWidgets.QLineEdit(self.pre_model)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_model_path.sizePolicy().hasHeightForWidth())
        self.pre_model_path.setSizePolicy(sizePolicy)
        self.pre_model_path.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pre_model_path.setFont(font)
        self.pre_model_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_model_path.setObjectName("pre_model_path")
        self.horizontalLayout_11.addWidget(self.pre_model_path)
        self.pre_model_button = QtWidgets.QPushButton(self.pre_model)
        self.pre_model_button.setStyleSheet("")
        self.pre_model_button.setText("")
        self.pre_model_button.setIcon(icon2)
        self.pre_model_button.setAutoRepeat(False)
        self.pre_model_button.setObjectName("pre_model_button")
        self.horizontalLayout_11.addWidget(self.pre_model_button)
        self.label_15 = QtWidgets.QLabel(self.page_8)
        self.label_15.setGeometry(QtCore.QRect(50, 180, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.stackedWidget_input.addWidget(self.page_8)
        self.verticalLayout_4.addWidget(self.input)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        self.stackedWidget_input.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.Description.setText(_translate("MainWindow", "1. Choose files and folder by pressing \"Browse button\".\n"
"2. Enter column name of data stream and label in file.\n"
"3. Press \"Execute button\" to start the training procedure."))
        self.Title.setText(_translate("MainWindow", "Review Paper AI Model Builder"))
        self.SecondTitle.setText(_translate("MainWindow", "This program generates AI model for a given tagged data."))
        self.Warning.setText(_translate("MainWindow", "PLEASE CLOSE any output files the program generates before executing"))
        self.Warning_2.setText(_translate("MainWindow", "PLEASE CLOSE any output files the program generates before executing"))
        self.SecondTitle_2.setText(_translate("MainWindow", "This program make prediction for a given tagged data."))
        self.Description_2.setText(_translate("MainWindow", "1. Choose files and folder by pressing \"Browse button\".\n"
"2. Enter column name of data stream and label in file.\n"
"3. Press \"Execute button\" to start the training procedure."))
        self.Title_2.setText(_translate("MainWindow", "Review Paper Predictor"))
        self.ab_col.setText(_translate("MainWindow", "Abstract"))
        self.label_7.setText(_translate("MainWindow", "Output folder"))
        self.bu_exeButton.setText(_translate("MainWindow", "E x e c u t e"))
        self.label_6.setText(_translate("MainWindow", "Word bank"))
        self.label_5.setText(_translate("MainWindow", "Input file"))
        self.label_8.setText(_translate("MainWindow", "Title"))
        self.label_10.setText(_translate("MainWindow", "Label"))
        self.label.setText(_translate("MainWindow", "Path"))
        self.label_2.setText(_translate("MainWindow", "Column name"))
        self.label_9.setText(_translate("MainWindow", "Input file"))
        self.pre_exeButton.setText(_translate("MainWindow", "E x e c u t e"))
        self.label_3.setText(_translate("MainWindow", "Path"))
        self.ab_col_2.setText(_translate("MainWindow", "Abstract"))
        self.label_4.setText(_translate("MainWindow", "Column name"))
        self.label_11.setText(_translate("MainWindow", "Output folder"))
        self.label_12.setText(_translate("MainWindow", "Title"))
        self.label_14.setText(_translate("MainWindow", "Word bank"))
        self.label_15.setText(_translate("MainWindow", "Model file"))

